### ISSUE TITLE
style.css not found

### ISSUE THREAD

**Issue by camhart** [JamesKyburz/dialogs#54]
Electron 8 - Mac OS Catalina (10.15.3) - from the main thread - asar enabled, built using electron-builder

```
[2020-03-30 20:23:12.350] [info] (32389) Error: ENOENT, style.css not found in /Applications/My.app/Contents/Resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at Object.<anonymous> (/Applications/My.app/Contents/Resources/app.asar/background.js:568:424635)
    at r (/Applications/My.app/Contents/Resources/app.asar/background.js:1:110)
    at click (/Applications/My.app/Contents/Resources/app.asar/background.js:568:453224)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13)
```

**Comment by danielovadia** [comment]
Can be solved by using brfs node module:
```
brfs node_modules/dialogs/index.js > node_modules/dialogs/index.js2
mv node_modules/dialogs/index.js2 node_modules/dialogs/index.js

```
